version: "3"
services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - 8094:8094
    networks:
      - mynetwork
  jenkins:
    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - mynetwork
networks:
  mynetwork:
